name: Setup workspace
description: Set up tools, install dependencies and set up references for Nx
runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        cache: npm
        cache-dependency-path: ./package-lock.json
        node-version-file: ./.tool-versions

    - name: Derive appropriate SHAs for base and head for `nx affected` commands
      uses: nrwl/nx-set-shas@v4

    - name: Install dependencies
      shell: bash
      run: npm ci
